import { getPages } from '@/lib/xata.pages'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'

export async function getStaticProps() {
  const res = await getPages()
  const paths = res.map((page) => page.slug)
  return {
    props: {
      title: 'Hello World static',
      routes: paths,
    },
  }
}

export default function Home({
  title,
  routes,
}: {
  title: string
  routes: string[]
}) {
  const [data, setData] = useState(null)

  const handleClick = async () => {
    const res = await fetch('/api/get-subs')
    const data = await res.json()
    setData(data)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{title}</h1>
        <br />
        <br />
        <p>Routes</p>
        <ul>
          {routes.map((route) => (
            <li key={route}>
              <Link href={`/${route}`}>{route}</Link>
            </li>
          ))}
        </ul>
        <br />
        <br />

        <hr />
        <br />
        <br />
        <p>Load latest content</p>
        <button onClick={handleClick}>Load</button>
        <br />
        <br />
        {data && <pre>{JSON.stringify(data, null, 2)}</pre>}
      </main>
    </>
  )
}
